// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "RMUTI",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
  

//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <div className="layout">
//             <header className="header">
//               <div>
//                 <img src="/images/header.png" height={90} alt="header" />
//               </div>
//             </header>
          
//             <main className="main-content">
//               {children}
//             </main>
//             <footer className="footer">
//               © 2024 RMUTI <br />
//               นักศึกษาวิทยาการคอม มหาวิทยาลัยเทคโนโลยีราชมงคลอีสาน
//             </footer>
          
//         </div>
//       </body>
//     </html>
//   );
// }

import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="layout">

          <main className="main-content">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}